{"metadata":{"kernelspec":{"language":"python","display_name":"Python 3","name":"python3"},"language_info":{"name":"python","version":"3.10.13","mimetype":"text/x-python","codemirror_mode":{"name":"ipython","version":3},"pygments_lexer":"ipython3","nbconvert_exporter":"python","file_extension":".py"},"kaggle":{"accelerator":"nvidiaTeslaT4","dataSources":[],"dockerImageVersionId":30733,"isInternetEnabled":true,"language":"python","sourceType":"notebook","isGpuEnabled":true}},"nbformat_minor":4,"nbformat":4,"cells":[{"cell_type":"markdown","source":"**README**\n\nThis document is prepared by the **Kaggle**.\n","metadata":{}},{"cell_type":"markdown","source":"# Install Packages","metadata":{}},{"cell_type":"code","source":"!pip install -q trl","metadata":{"execution":{"iopub.status.busy":"2024-06-26T09:21:16.376020Z","iopub.execute_input":"2024-06-26T09:21:16.376430Z","iopub.status.idle":"2024-06-26T09:21:31.211638Z","shell.execute_reply.started":"2024-06-26T09:21:16.376400Z","shell.execute_reply":"2024-06-26T09:21:31.210459Z"},"trusted":true},"execution_count":9,"outputs":[{"name":"stdout","text":"\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\nkfp 2.5.0 requires google-cloud-storage<3,>=2.2.1, but you have google-cloud-storage 1.44.0 which is incompatible.\u001b[0m\u001b[31m\n\u001b[0m","output_type":"stream"}]},{"cell_type":"code","source":"from datasets import load_dataset\nfrom huggingface_hub import login","metadata":{"execution":{"iopub.status.busy":"2024-06-26T09:21:11.372557Z","iopub.execute_input":"2024-06-26T09:21:11.373436Z","iopub.status.idle":"2024-06-26T09:21:11.377565Z","shell.execute_reply.started":"2024-06-26T09:21:11.373403Z","shell.execute_reply":"2024-06-26T09:21:11.376478Z"},"trusted":true},"execution_count":8,"outputs":[]}]}